### ISSUE TITLE
[PE-D][Tester D] Splitted expenses settled, but not display in list of expenses

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T12-3/tp#175]
![image.png](https://raw.githubusercontent.com/T0nyLin/ped/main/files/6784f401-5300-4fae-abcd-a27a466a0ff9.png)

Not sure what I supposed to happen after settling the split expense, but I believe it should be added to overall list of expenses.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: T0nyLin/ped#10

**Comment by yyangdaa** [comment]
This is issue is due to the lack of information in the user guide for new users to understand how to navigate in the app. The updated name for split expense is "Shared Bills" to prevent the misconception that it belongs to the same class as expenses.
